//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsconfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tsconfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ddraw]
        ///RealDDrawPath=AUTO
        ///BltMirror=0
        ///BltNoTearing=0
        ///ColorFix=0
        ///DisableHighDpiScaling=0
        ///FakeVsync=0
        ///FakeVsyncInterval=0
        ///ForceBltNoTearing=0
        ///ForceDirectDrawEmulation=0
        ///NoVideoMemory=0
        ///SingleProcAffinity=0
        ///ShowFPS=0
        ///.
        /// </summary>
        internal static string aqrit {
            get {
                return ResourceManager.GetString("aqrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddraw {
            get {
                object obj = ResourceManager.GetObject("ddraw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddwrapper {
            get {
                object obj = ResourceManager.GetObject("ddwrapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libwine {
            get {
                object obj = ResourceManager.GetObject("libwine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Intro]
        ///PlaySide01=no
        ///PlaySide00=yes
        ///
        ///[Options]
        ///GameSpeed=1
        ///Difficulty=1
        ///ScrollMethod=0
        ///ScrollRate=6
        ///AutoScroll=yes
        ///DetailLevel=2
        ///UnitActionLines=yes
        ///ToolTips=yes
        ///
        ///[Video]
        ///AllowHiResModes=yes
        ///ScreenWidth=800
        ///ScreenHeight=600
        ///StretchMovies=no
        ///
        ///[MultiPlayer]
        ///PhoneIndex=-1
        ///Color=0
        ///Side=GDI
        ///Handle=
        ///PreferredServer=XWIS
        ///Locale=
        ///StoreNick=yes
        ///LastNickSlot=-1
        ///
        ///[Audio]
        ///SoundVolume=0.300000
        ///VoiceVolume=0.300000
        ///ScoreVolume=0.300000
        ///IsScoreRepeat=no
        ///IsScoreShuffle=yes
        ///SoundLatency= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SUN_ini {
            get {
                return ResourceManager.GetString("SUN_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tsconfig_icon {
            get {
                object obj = ResourceManager.GetObject("tsconfig_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tsddraw {
            get {
                object obj = ResourceManager.GetObject("tsddraw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wined3d {
            get {
                object obj = ResourceManager.GetObject("wined3d", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
